#
# docker-compose.yml
#
# FOR CI ONLY.
#
#   Using Docker Compose helps us test the library on both Node 14 and Node 16. The purpose is _not_ to burden the
#   developer experience (and documentation) with Docker. This file is only used for CI.
#
# Context:
#   - Cloud Build, with 'firebase-ci-builder' image in the Container Registry
#
# Environment values (Cloud Build):
#   - 'CI_BUILDER_IMAGE'
#   - 'NODE': "14"
#
#   - pwd: /workspace
#
# Intentions:
#   - Test with Node 14
#   - Test with Node 16
#
# Docker Compose (v3) note:
#   BE CAREFUL with use of pipe ('|') or '&&' in the commands! See -> https://stackoverflow.com/a/68590318/14455
#
# References:
#   Overview of Docker Compose (Docker docs)
#     -> https://docs.docker.com/compose/
#   Compose file version 3 reference
#     -> https://docs.docker.com/compose/compose-file/compose-file-v3/
#
version: '3.0'

services:
  # Launch Firebase Emulators, with certain warning and info messages suppressed.
  #
  emul:
    image: ${CI_BUILDER_IMAGE:-firebase-ci-builder:9.16.0-node16-npm7}
    ports:
      - "4000:4000"
      - "5002:5002"
      - "6767:6767"
      # Keep ports aligned with 'firebase.json'
    volumes:
      - .:/work
    working_dir: /work
    command: bash -o pipefail -c
      'echo "Launching Docker... üê≥" &&
      firebase emulators:start --project=demo-1
        | grep -v -E "Detected demo project ID|You are not signed in to the Firebase CLI|You are not currently authenticated"'
      # Keep project ID in sync with 'package.json' and 'sample/test-fns/setup.jest.js'
    environment:
      - DEBUG_COLOR=1

  # Wrap 'emul' in a blanket, to Warm it UP!
  #
  # Firebase Emulators are SLOW to wake. This part runs a minimal set of tests (the results of which are not used),
  # to wake up the necessary subsystems server-side. This should result in more dependable test times in the actual
  # tests.
  #
  blanket:
    build:
      context: ci/dc-tools/n-user/
      args:
        - NODE=${NODE:-16}
    volumes:
      - .:/work
    working_dir: /work
    command: sh -o pipefail -c
      'wait-for-it emul:6767 &&
      npm run ci:warm-up &&
      ack-trigger 1
      '
    environment: ['EMUL_HOST=emul']
    #
    depends_on: ['emul']
    profiles: ['manual']     # could also be automatic (then it'll launch with 'docker compose up')

  # Test with any supported Node version
  #
  # Note:
  #   CI has already done 'npm install'. It did so as root; we only have read access.
  #
  test:
    build:
      context: ci/dc-tools/n-user/
      args:
        - NODE=${NODE:-16}
    volumes:
      - .:/work
    working_dir: /work
    command: sh -o pipefail -c
      'ack-await 1 &&
      npm run ci:test
      '
    environment: ['EMUL_HOST=emul']
      #
    depends_on: ['emul', 'blanket']
    profiles: ['manual']
